version: 2.1
jobs:
  build_tests:
  docker:
    -image: circleci/node:12
  steps:

    -checkout
    -run:

    name: Install npm dependencies

    command: |

      npm install --save

  build docker image:

    docker:

      -image: circleci/node:12

      steps:

  -checkout

      -setup_remote_docker:

          docker layer caching: false

      -run:

name: Build Docker image

command: |

docker build -t nodejawebapp -t adi/nodejawebapp:latest. 
echo $DOCKER_PASSWORD | docker login -u adi --password-stdin)

docker push adi/nodejawebappilatest

workflowns:

  build tests:
    jobs:
      -build_tests

      -build docker_image
